# Generated by Django 4.2.16 on 2025-11-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
    ]
